### ISSUE TITLE
Fatal error: Does not load from file

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#119]
Saved Microscope at Tier 1
Attempted to Load from Repository at same Tier
See attached errors

Same happened upon Load from File

**Comment by strambc** [comment]
[
![Issue 119_Error 1](https://user-images.githubusercontent.com/4050585/102378767-2564ba00-3f94-11eb-87a8-3ceb409d3e06.png)
![Issue 119_Error 2](https://user-images.githubusercontent.com/4050585/102378769-2564ba00-3f94-11eb-8bcb-0682a146de1b.png)

](url)

**Comment by strambc** [comment]
**Errors from Load from File**

[
![Issue 119_Error 3](https://user-images.githubusercontent.com/4050585/102379269-b340a500-3f94-11eb-9fb8-e9778e639dc0.png)
![Issue 119_Error 4](https://user-images.githubusercontent.com/4050585/102379270-b340a500-3f94-11eb-91d0-18ed3f3a0499.png)

](url)

**Comment by Akramhar** [comment]
this should be fixed in 0.31.
in addition microscope from older version should be somewhat adjusted at least for what concern the MicroscopeStand and the version getting updated.
There are still issues in following cases:
1) a schema name was changed : during the load phase components whose model cannot be found are discarded
2) fields are renamed / removed : the value may persist (needs to be verified) even though they are not accessible in the editor form
